name: tocsa_dart_frog
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.0
  firedart: ^0.9.8
  http: ^1.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
